[package]
authors = ["Cody Weaver cody.weaver@colorado.edu"]
name = "greprs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.10.2"
